export const PRODUCTS_DATA = "PRODUCTS_DATA";
export const PRICE_PRODUCT = "PRICE_PRODUCT";
export const SET_URL_IMAGE = "SET_URL_IMAGE";
export const CHANGE_THEME = "CHANGE_THEME";



// USER /////
export const SET_SIGN_IN = "SET_SIGN_IN";
export const ADD_TASK_FAVORITE = "SET_TASK_FAVORITE";
export const DELETE_TASK_FAVORITE = "DELETE_TASK_FAVORITE";
export const SET_TASK_FAVORITE = "SET_TASK_FAVORITE";


